name: Check

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true
          require-lockfile: true
      - run: pnpm check
